language: python
python:
   - "3.6"
   - "3.7"
install:
  - pip install -r requirements.txt
script:
    - python python/tsv_to_sbml.py
    - python python/basic_fba.py
    - python python/restricted_fba.py