language: python
python:
   - "3.6"
   - "3.7"
branches:
  only:
    - devel
install:
  - pip install -r requirements.txt
script:
    - python python/tsv_to_sbml.py
    - python python/basic_fba.py
    - python python/restricted_fba.py
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: devel
  target_branch: devel-build