language: python
python:
   - "3.7"
branches:
  only:
    - devel
install:
  - pip install -r requirements.txt
script:
    - python python/tsv_to_sbml.py
    - python python/basic_fba.py
    - python python/restricted_fba.py
    - travis_wait 30 memote report snapshot test_model.xml
    - python python/manage_reports.py
    - 'if [ "$TRAVIS_PULL_REQUEST" != "true" ]; then bash ./report.sh; fi'


deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    on:
      branch: devel
      condition: $TRAVIS_PYTHON_VERSION = "3.7"
    target_branch: gh-pages

